### ISSUE TITLE
Hive: fix HiveTableTest#testListTables failure

### ISSUE THREAD

**Issue by vanliu-tx** [BKBASE-Plugin/iceberg#18]
```
> Task :iceberg-hive-metastore:test

org.apache.iceberg.hive.HiveTableTest > testListTables FAILED
    java.lang.AssertionError: should only 1 iceberg table . expected:<1> but was:<2>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.apache.iceberg.hive.HiveTableTest.testListTables(HiveTableTest.java:326)
```

**Comment by vanliu-tx** [comment]
done
