### ISSUE TITLE
Flink: stream rewrite failed in some cases

### ISSUE THREAD

**Issue by vanliu-tx** [BKBASE-Plugin/iceberg#38]
```
2022-05-13 11:18:17,872 INFO  org.apache.iceberg.flink.sink.IcebergRewriteFilesCommitter   [] - Committing rewrite file groups of table iceberg_hive_catalog.iceberg_2005000727.mysqlcdc_van_7010_2005000727: RewriteResult{partitions=[PartitionData{id_trunc=1200000, ____et_month=626}], startingSnapshotId=8635809729983299546, numRewrittenFiles=2, numAddedFiles=1}.
2022-05-13 11:18:18,254 ERROR org.apache.iceberg.flink.sink.IcebergRewriteFilesCommitter   [] - Cannot commit rewrite file groups, attempting to clean up written files.
org.apache.iceberg.exceptions.ValidationException: Missing required files to delete: hdfs://testOnline/data/iceberg/warehouse/iceberg_2005000727.db/mysqlcdc_van_7010_2005000727/data/id_trunc=1200000/____et_month=2022-03/00000-0-f95888c5-64e0-4747-82fa-81cc533ec8d9-00057.parquet,hdfs://testOnline/data/iceberg/warehouse/iceberg_2005000727.db/mysqlcdc_van_7010_2005000727/data/id_trunc=1200000/____et_month=2022-03/00000-0-f95888c5-64e0-4747-82fa-81cc533ec8d9-00059.parquet
        at org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:46) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.ManifestFilterManager.validateRequiredDeletes(ManifestFilterManager.java:227) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.ManifestFilterManager.filterManifests(ManifestFilterManager.java:190) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.MergingSnapshotProducer.apply(MergingSnapshotProducer.java:517) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:164) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:283) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.util.Tasks$Builder.runTaskWithRetry(Tasks.java:404) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.util.Tasks$Builder.runSingleThreaded(Tasks.java:214) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:198) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.util.Tasks$Builder.run(Tasks.java:190) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.SnapshotProducer.commit(SnapshotProducer.java:282) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.flink.sink.IcebergRewriteFilesCommitter.commitRewriteResult(IcebergRewriteFilesCommitter.java:104) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.flink.sink.IcebergRewriteFilesCommitter.commitRewriteResults(IcebergRewriteFilesCommitter.java:90) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.iceberg.flink.sink.IcebergRewriteFilesCommitter.snapshotState(IcebergRewriteFilesCommitter.java:72) ~[blob_p-18eaa50b994da682c46635771ae4356412f1b414-6517ea91cf6e0520f8de477c5dbe5f6a:?]
        at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:219) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.snapshotState(StreamOperatorStateHandler.java:170) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator.snapshotState(AbstractStreamOperator.java:348) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.checkpointStreamOperator(RegularOperatorChain.java:233) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.buildOperatorSnapshotFutures(RegularOperatorChain.java:206) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.RegularOperatorChain.snapshotState(RegularOperatorChain.java:186) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.takeSnapshotSync(SubtaskCheckpointCoordinatorImpl.java:605) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.checkpointState(SubtaskCheckpointCoordinatorImpl.java:315) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$performCheckpoint$14(StreamTask.java:1329) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$1.runThrowing(StreamTaskActionExecutor.java:50) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.performCheckpoint(StreamTask.java:1315) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.triggerCheckpointOnBarrier(StreamTask.java:1258) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointBarrierHandler.notifyCheckpoint(CheckpointBarrierHandler.java:147) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.triggerCheckpoint(SingleCheckpointBarrierHandler.java:287) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.access$100(SingleCheckpointBarrierHandler.java:64) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler$ControllerImpl.triggerGlobalCheckpoint(SingleCheckpointBarrierHandler.java:493) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.triggerGlobalCheckpoint(AbstractAlignedBarrierHandlerState.java:74) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.AbstractAlignedBarrierHandlerState.barrierReceived(AbstractAlignedBarrierHandlerState.java:66) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.lambda$processBarrier$2(SingleCheckpointBarrierHandler.java:234) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.markCheckpointAlignedAndTransformState(SingleCheckpointBarrierHandler.java:262) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.SingleCheckpointBarrierHandler.processBarrier(SingleCheckpointBarrierHandler.java:231) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.handleEvent(CheckpointedInputGate.java:181) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.checkpointing.CheckpointedInputGate.pollNext(CheckpointedInputGate.java:159) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.AbstractStreamTaskNetworkInput.emitNext(AbstractStreamTaskNetworkInput.java:110) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:65) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:496) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:203) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:809) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:761) ~[flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.runWithSystemExitMonitoring(Task.java:958) [flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.restoreAndInvoke(Task.java:937) [flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:766) [flink-dist_2.11-1.14.3.jar:1.14.3]
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:575) [flink-dist_2.11-1.14.3.jar:1.14.3]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
```

**Comment by vanliu-tx** [comment]
RewriteFileGroup中包含重复文件

```
IcebergRewriteTaskEmitter      [] - can pick? true 0 RewriteFileGroup{latestSequenceNumber=224, latestSnapshotId=9214289341116275201, partition=PartitionData{id_bucket=3, ____et_month=628}, rewriteFilesSize=200627, totalFilesCount=20}
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00001.parquet, delete files 7
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00003.parquet, delete files 6
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00005.parquet, delete files 5
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00007.parquet, delete files 4
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00009.parquet, delete files 3
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00011.parquet, delete files 2
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00013.parquet, delete files 1
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-0-29b698ee-304d-4de8-82df-503256b2c485-00015.parquet, delete files 0
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00001.parquet, delete files 20
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00001.parquet, delete files 20
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00004.parquet, delete files 16
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00004.parquet, delete files 16
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00006.parquet, delete files 14
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00006.parquet, delete files 14
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00008.parquet, delete files 12
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00008.parquet, delete files 12
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00010.parquet, delete files 10
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00010.parquet, delete files 10
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00012.parquet, delete files 8
IcebergRewriteTaskEmitter      [] - hdfs://tb/data/id_bucket=3/____et_month=2022-05/00000-51772-3c7e1bf0-e3a1-4238-b1b0-332862c41208-00012.parquet, delete files 8
IcebergRewriteTaskEmitter      [] - Emit rewrite task: RewriteTask{snapshotId=9214289341116275201, partition=PartitionData{id_bucket=3, ____et_month=628}, totalFilesCount=20, totalSizeInBytes=200547}.
```

**Comment by vanliu-tx** [comment]
任务停止后再启动，从save point中恢复时会遍历snapshot中未被重写的数据文件，将其重写并尝试在下一次checkpoint中commit。这里cdc任务恢复后会读取binlog，并在接下来第一次checkpoint中提交数据文件，这批数据文件里有非常大的可能性包含delete-files，导致在下一次checkpoint时提交的重写数据文件校验失败，从而做无用功。

这里考虑从save point恢复时，跳过历史的snapshot，不对这些数据文件进行流式重写。转而依赖另外的flink/spark任务将全表进行重写。
